cb 4 (Реализовать страницу пользователя)
Casablanca2021/yandex.praktikum.game pull request #19
Opened 2021-03-23 11:08 UTC by kerimov95

2021-03-23 13:11 UTC, artNikulin commented on src/components/Profile/Profile.tsx
> +/* eslint-disable camelcase */
Это правило надо наверное отключить в конфиге линта, у нас много где будет через нижнее подчеркивание

2021-03-23 13:20 UTC, artNikulin commented on src/components/Profile/Profile.tsx
> +/* eslint-disable @typescript-eslint/ban-types */
И давай может вынесем все страницы в отдельную папку, pages например, а в папке components оставим общие, которые с kjubrjq (без ui)

2021-03-23 13:53 UTC, artNikulin commented on src/components/Profile/Profile.tsx
> +            label="Ник"
Я создам словарик в своем ПР, предлагаю потом переписать такие вещи на получение значения из словаря

2021-03-23 14:07 UTC, artNikulin commented on src/components/Profile/Profile.tsx
> +    const { state } = this;
Интересная запись, обычно деструктурируют state или props (или еще что-то более вложенное)

2021-03-23 14:12 UTC, artNikulin commented on src/components/Profile/Profile.tsx
> +    const src = state.profile?.avatar || 'https://more-show.ru/upload/not-available.png';
Кажется здесь optional chaining излишний, ведь у нас всегда есть объект `profile` в state, пусть даже и пустой, лучше добавить как раз `profile` в деструктуризацию выше, и `isError` тоже

2021-03-23 15:31 UTC, artNikulin commented on src/components/Profile/types.tsx
> +type profileValidations = {
Тут тоже можно объявить через `Partial<profile>`, и лучше наверное сначала в начале объявить тип Profile (я бы назвал его с большой буквы), а затем его производные

2021-03-23 20:06 UTC, kerimov95 commented on src/components/Profile/Profile.tsx
> +/* eslint-disable @typescript-eslint/ban-types */
🎉

2021-03-23 20:06 UTC, kerimov95 commented on src/components/Profile/Profile.tsx
> +    const src = state.profile?.avatar || 'https://more-show.ru/upload/not-available.png';
🎉

2021-03-23 20:06 UTC, kerimov95 commented on src/components/Profile/Profile.tsx
> +            label="Ник"
🎉

2021-03-23 20:07 UTC, kerimov95 commented on src/components/Profile/types.tsx
> +type profileValidations = {
🎉

2021-03-23 20:07 UTC, kerimov95 commented on src/components/Profile/Profile.tsx
> +    const { state } = this;
🎉

2021-03-23 20:08 UTC, kerimov95 commented on src/components/Profile/Profile.tsx
> +/* eslint-disable camelcase */
🎉

2021-03-24 07:55 UTC, artNikulin commented on src/pages/Profile/types.tsx
> +type Profile = {
Правки вижу, все отлично

2021-03-24 07:55 UTC, artNikulin approved these changes

2021-03-25 12:38 UTC, artNikulin commented on src/pages/Profile/Profile.tsx
> +import React, { PureComponent } from 'react';
Не очень понятно только как менять пароль пользователя

2021-03-25 16:20 UTC, spt30 requested changes

2021-03-25 16:20 UTC, spt30 commented on .eslintrc.json
> +        "camelcase" : "off",
правила линтера не зря придуманы, и они, как правило, очень полезные

расскажи, пожалуйста, зачем выключать ban-types? и camelcase тем более?

2021-03-25 16:20 UTC, spt30 commented on src/pages/Profile/Profile.css
> +}
про настройку IDE для оконечных строк файла уже говорил

2021-03-25 16:20 UTC, spt30 commented on src/pages/Profile/Profile.css
> +}
если у вас postcss, может хотите использовать nested-css?

2021-03-25 16:20 UTC, spt30 commented on src/pages/Profile/types.tsx
> +type profileValidations = Record<keyof Profile, boolean>
типы лучше именовать в PascalCase

2021-03-25 16:20 UTC, spt30 commented on src/pages/Profile/types.tsx
> +    isError: Partial<profileValidations>;
все-таки с префиксами is, has, have начинаются те переменные, которые имеют тип boolean

тут объект — давай переименуем в `errors`

2021-03-25 16:20 UTC, spt30 commented on src/pages/Profile/Profile.tsx
> +  handleUserInput = (e : React.ChangeEvent<HTMLInputElement>): void => {
`React.ChangeEvent<HTMLInputElement>` можно вынести в отдельный именованный тип и не писать каждый раз

2021-03-25 16:20 UTC, spt30 commented on src/pages/Profile/Profile.tsx
> +  }
❗ так нельзя обновлять state компонента

необходимо передать в setState функцию обратного вызова, которая на вход примет состояние и вернет объект
иначе можно нарваться на коллизию обновлений стейта

читайте [документацию](https://ru.reactjs.org/docs/faq-state.html#how-do-i-update-state-with-values-that-depend-on-the-current-state)

2021-03-25 16:20 UTC, spt30 commented on src/pages/Profile/Profile.tsx
> +            label="Телефон"
Лучше заранее позаботиться о себе будущем и все, что относится к текстовому пользовательскому контенту вынести в отдельный файл (просто пусть там хранится объект texts)
Это сильно поможет, когда вам внезапно потребуется сделать переводы — не придется бегать по огромному приложению и искать, где же там какой title у кнопки завалялся непереведенный

2021-03-26 07:25 UTC, kerimov95 commented on .eslintrc.json
> +        "camelcase" : "off",
🎉

2021-03-26 07:26 UTC, kerimov95 commented on src/pages/Profile/types.tsx
> +type profileValidations = Record<keyof Profile, boolean>
🎉

2021-03-26 07:29 UTC, kerimov95 commented on src/pages/Profile/types.tsx
> +    isError: Partial<profileValidations>;
🎉

2021-03-26 07:30 UTC, kerimov95 commented on src/pages/Profile/Profile.tsx
> +  handleUserInput = (e : React.ChangeEvent<HTMLInputElement>): void => {
🎉

2021-03-26 07:37 UTC, kerimov95 commented on src/pages/Profile/Profile.tsx
> +  }
🎉

2021-03-26 07:54 UTC, kerimov95 commented on src/pages/Profile/Profile.tsx
> +            label="Телефон"
🎉

2021-03-28 11:04 UTC, spt30 approved these changes

2021-03-28 12:45 UTC, kerimov95 commented on src/pages/Profile/Profile.css
> +}
🎉

2021-03-28 12:45 UTC, kerimov95 commented on src/pages/Profile/Profile.css
> +}
🎉

2021-03-28 12:50 UTC, merged