Cb-10  (Создать страницу лидерборда)
Casablanca2021/yandex.praktikum.game pull request #22
Opened 2021-03-24 12:27 UTC by kerimov95

2021-03-24 12:51 UTC, artNikulin approved these changes
Все отлично👌

2021-03-25 16:40 UTC, spt30 requested changes
`.DS_Store` нужно добавить в gitignore во всех папках

2021-03-25 16:40 UTC, spt30 commented on src/pages/Leaderboard/Leaderboard.tsx
> +    leaders?.splice(leaders.length - 2, leaders.length - 1);
splice модифицирует массив;
массив хранится по ссылке в state компонента;
здесь ты явно мутируешь стейт, что делать запрещено;

нужно сначала создать копию, а затем ее мутировать и вставить в state

2021-03-25 16:40 UTC, spt30 commented on src/pages/Leaderboard/Leaderboard.tsx
> +    leaders?.splice(leaders.length - 2, leaders.length - 1);
более того, ты можешь получить не ту копию, что ожидаешь
как использовать предыдущее значение при обновлении стейта и почему нельзя так, как здесь, можно почитать [тут](https://ru.reactjs.org/docs/faq-state.html#how-do-i-update-state-with-values-that-depend-on-the-current-state)

2021-03-25 16:40 UTC, spt30 commented on src/pages/Leaderboard/Leaderboard.tsx
> +    });
Хорошо составлена заглушка 👍 
Это важный навык на самом деле — проектировать стабы так, чтобы при встрече с реальным апи ничего не сломалось: здесь и пробелы, и повтор имен, и широкий разброс количества очков

Я бы еще добавил имена покороче и подлиннее, имена на латинице и со спецсимволами, а также в паре объектов одинаковое количество очков

2021-03-26 09:02 UTC, kerimov95 commented on src/pages/Leaderboard/Leaderboard.tsx
> +    leaders?.splice(leaders.length - 2, leaders.length - 1);
🎉

2021-03-26 09:03 UTC, kerimov95 commented on src/pages/Leaderboard/Leaderboard.tsx
> +    });
🎉

2021-03-28 11:07 UTC, spt30 requested changes
![image](https://user-images.githubusercontent.com/31798669/112750015-6c286e00-8fdf-11eb-8d28-98fbded7b62f.png)

.DS_Store все еще есть

2021-03-29 06:55 UTC, spt30 approved these changes

2021-03-29 07:51 UTC, merged