cb-8 (Реализовать страницу форума.)
Casablanca2021/yandex.praktikum.game pull request #31
Opened 2021-03-28 21:12 UTC by nexaq

2021-03-29 13:20 UTC, artNikulin commented on src/components/Layout/Layout.tsx
> +  let {transparent, children} = props;
Переменные и методы, которые не стоит мутировать, лучше объявлять через `const`

2021-03-29 13:49 UTC, artNikulin commented on src/components/MainMenu/MainMenu.tsx
> +      name: 'Home',
Названия лучше на русском и через dictionary сделать

2021-03-29 15:06 UTC, artNikulin commented on src/components/MainMenu/MainMenu.tsx
> +        onClick={() => {
Здесь наверное тоже через `handleClick` имеет смысл сделать

2021-03-29 15:27 UTC, artNikulin commented on src/components/MainMenu/MainMenu.tsx
> +const MainMenu: FC = () => {
Меню это круто, но надо как-то по стилю и расположению договорится, сейчас данный вариант непонятно как будет сочетаться с главной страницей

2021-03-30 09:19 UTC, artNikulin commented on src/components/App/App.tsx
> +import ForumView from "pages/ForumView/index";
Достаточно написать `from "pages/ForumView"`;

2021-03-30 09:24 UTC, artNikulin commented on src/components/MainMenu/index.ts
> +import MainMenu from './MainMenu';
Во всех файлах по разному export default делается, выбери либо этот вариант либо `export {default} from...`,
лучше ориентироваться как в других файлах уже делали

2021-03-30 09:41 UTC, artNikulin commented on src/components/MainMenu/MainMenu.tsx
> +  let handleClick = (path: string) => {
Думаю лучше сделать что-то типо такого
`const handleClick = (path: string) => () => history.push(path);`

2021-03-30 09:42 UTC, artNikulin commented on src/components/MainMenu/MainMenu.tsx
> +        onClick={() => handleClick(item.path)}
А тут оставить просто `handleClick(item.path)`

2021-03-30 12:06 UTC, artNikulin commented on src/components/App/App.css
> +    background-image: linear-gradient(to right top, #e5e5e5, #d4d4d4, #c2c2c2, #b2b2b2, #a1a1a1);
Можно сделать цвет более светлый, так немного давит

2021-03-30 12:49 UTC, artNikulin commented on src/components/Layout/Layout.tsx
> +      return <div>
Здесь `div` точно нужен?

2021-03-30 12:51 UTC, artNikulin commented on src/components/Layout/Layout.tsx
> +      {renderTitle()}
Проще тут сразу написать `props.title && <Header .../>`, нежели делать это отдельной функцией, да еще и без особой логики внутри

2021-03-30 12:54 UTC, artNikulin commented on src/components/Layout/Layout.css
> +.layout__app-name {
Это правило с верхним можно объединить

2021-03-30 12:55 UTC, artNikulin commented on src/components/Layout/Layout.css
> +.layout__app-name:hover {
Вроде бы добавили postcss-nested, поэтому надо сгруппировать с верхним правилом

2021-03-30 12:55 UTC, artNikulin commented on src/pages/Forum/components/LabelList/LabelList.css
> +.label-list__item {
Тут тоже сгруппировать надо правила

2021-03-30 13:00 UTC, artNikulin commented on src/pages/Forum/components/LabelList/LabelList.tsx
> +        return <Link to={item.path} key = {key} className={`label-list__item ${item.active === true ? 'label-list__item_active' : ''}`}>{item.name}</Link>
`item.active` и так `boolean`, можно не сравнивать с `true`

2021-03-30 13:02 UTC, artNikulin commented on src/pages/SignUp/SignUp.css
> -.app {
Без этого не будет выравнивания по центру экрана

2021-03-30 13:12 UTC, artNikulin commented on src/pages/SignUp/SignUp.tsx
> +    <Layout transparent={true}>
Надо добавить наверное это не только на регистрацию

2021-03-30 13:14 UTC, artNikulin approved these changes

2021-03-30 18:56 UTC, artNikulin commented on src/components/MainMenu/MainMenu.tsx
> +  let activeItem = useLocation().pathname;
Про `const` забыл

2021-04-01 22:44 UTC, spt30 commented on src/pages/Forum/Forum.tsx
> +  let categories: CategoryItems = [
все эти переменные можно вынести за пределы компонента

2021-04-01 22:44 UTC, spt30 commented on src/pages/Forum/components/LabelList/LabelList.css
> +    padding: 4px 7px;
не понятно: где-то у тебя отступы с шагом в 5px (5px 10px), где-то в 2px, а тут вообще непонятно что
хотелось бы какой-то консистентности

2021-04-01 22:44 UTC, spt30 commented on src/pages/Forum/components/LabelList/LabelList.tsx
> +        return <Link to={item.path} key = {key} className={`label-list__item ${item.active ? 'label-list__item_active' : ''}`}>{item.name}</Link>
`key = {key}`?????????

2021-04-01 22:44 UTC, spt30 commented on src/pages/Forum/components/LabelList/LabelList.tsx
> +        return <Link to={item.path} key = {key} className={`label-list__item ${item.active ? 'label-list__item_active' : ''}`}>{item.name}</Link>
пробелы лишние в смысле.

2021-04-01 22:44 UTC, spt30 commented on src/pages/Forum/components/LabelList/LabelList.tsx
> +        return <Link to={item.path} key = {key} className={`label-list__item ${item.active ? 'label-list__item_active' : ''}`}>{item.name}</Link>
Также круто было бы взять какую-нибудь библиотеку типа https://www.npmjs.com/package/b_

2021-04-02 18:49 UTC, spt30 requested changes

2021-04-02 18:49 UTC, spt30 commented on src/pages/Forum/Forum.tsx
> +    return item;
бессмысленно тут что-то возвращать, а также использовать map
используй `for ... of`

2021-04-02 18:49 UTC, spt30 commented on src/pages/Forum/Forum.tsx
>    let forumItems: (ForumItem & {categoryId?: string})[] = [
Это тоже можно вынести из компонента

2021-04-03 10:42 UTC, spt30 commented
Поговорили в личке

![Screenshot_20210403-154104_Slack.jpg](https://user-images.githubusercontent.com/31798669/113476138-f7e44380-9492-11eb-8cca-72d7f5bab383.jpg)

@artNikulin @kerimov95 кстати, тоже рекомендую почитать https://refactoring.guru/ru/smells/
Возможно конкретно в связке реакт+тайпскрипт не все имеет место быть, но иметь ввиду стоит

2021-04-03 11:02 UTC, spt30 commented
UPD: https://refactoring.guru/ru/refactoring/smells

2021-04-03 13:04 UTC, spt30 approved these changes

2021-04-04 14:07 UTC, artNikulin approved these changes

2021-04-05 08:42 UTC, merged