Cb 6 (Реализовать механику игры, )
Casablanca2021/yandex.praktikum.game pull request #33
Opened 2021-03-31 11:25 UTC by kerimov95

2021-03-31 17:59 UTC, artNikulin commented on src/pages/Game/Game.tsx
> +  width = 500;
Такие вещи тоже лучше куда то выносить, например в `const.ts` и назвать `canvasWidth`

2021-03-31 18:01 UTC, artNikulin commented on src/pages/Game/Game.tsx
> +  InitGame(): void {
Название метода лучше оставить в общем стиле с маленькой буквы)

2021-03-31 18:04 UTC, artNikulin commented on src/pages/Game/Game.tsx
> +  private Update(now: number): void {
Тут тоже с маленькой можно

2021-03-31 18:11 UTC, artNikulin commented on src/pages/Game/Game.tsx
> +    const modal = ModalWindow(modalStatus,
Вот тут как раз можно вынести отдельно в метод типа `renderModalWindow`

2021-03-31 19:27 UTC, artNikulin commented on src/pages/Game/types.ts
> +  private speed = 30;
Все числовые константы лучше вынести в `consts.ts` и назвать понятно, чтобы было ясно их применение

2021-03-31 19:28 UTC, artNikulin commented on src/pages/Game/types.ts
> +    for (let i = 0; i < 2; i += 1) {
Здесь можно оставить коммент, так с ходу непонятно что за магический цикл и цифра 2 в нем)

2021-03-31 19:30 UTC, artNikulin commented on src/pages/Game/types.ts
> +import logo from 'assets/Road.png';
Вообще странно почему два класса в одном файле с названием `types.ts`

2021-03-31 19:58 UTC, artNikulin commented on src/pages/Game/types.ts
> +    animate((time: number) => time + 5, this.setX.bind(this), 300, -1)
Можно объявить setX через стрелочную функцию и bind не нужен

2021-03-31 20:03 UTC, artNikulin commented on src/pages/Game/types.ts
> +    this.ctx?.clearRect(0, 0, this.width, this.height);
Наверное проще проверить` this.ctx` в `if` и потом уже использовать без `optional chaining` несколько раз

2021-03-31 20:12 UTC, artNikulin commented on src/utils/animate.ts
> +export const animate = (Timing: timing, Draw: draw, duration: number, Sign: sign = 1): void => {
Кажется надо наоборот переменные с маленькой буквы, типы с большой)

2021-03-31 20:22 UTC, artNikulin commented on src/pages/Game/types.ts
> +    let x = this.x + value;
Мне кажется читабельнее было бы через `const` и `switch` сделать

2021-03-31 20:26 UTC, artNikulin commented on src/utils/animate.ts
> +    if (timeFraction > 1) timeFraction = 1;
Ставь пустые строки между объявлением и конструкциями, так читабельнее, плюс я бы добавил правило, чтобы условие было в `{}`, пусть даже и одна строка

2021-04-01 09:59 UTC, artNikulin commented on src/pages/Game/Game.tsx
> +export class Game extends PureComponent<Props, { modalStatus: boolean }> {
Тут наверное лучше просто передать `{}` как тип пропсов и убрать тип из описания выше

2021-04-01 10:00 UTC, artNikulin commented on src/pages/Game/Game.tsx
> +  fps: number = 1000 / 120;
А почему не 1000/60? Это вроде 60 fps
Это получается еще чаще будет обновляться?

2021-04-01 10:07 UTC, artNikulin commented on src/pages/Game/Game.css
> +.form{
Нельзя так глобально классы объявлять, они у тебя перетрут все на других страницах, сделай общий класс для своей страницы и в рамках него добавляй остальные

2021-04-01 10:37 UTC, artNikulin commented on src/pages/Game/Game.tsx
> +    setTimeout(() => {
Сложная конструкция)

2021-04-01 10:49 UTC, artNikulin approved these changes

2021-04-02 14:19 UTC, spt30 requested changes
опять что-то с .gitignore

![Снимок экрана 2021-04-02 в 19 12 10](https://user-images.githubusercontent.com/31798669/113423097-53f18e00-93e7-11eb-8e6d-89048eb35f71.png)

Также пролайкал комментарии Артема, считаю, что их тоже нужно поправить

2021-04-02 14:19 UTC, spt30 commented on src/pages/Game/Game.tsx
> +  width = 500;
Можно просто в начало компонента вынести

2021-04-02 14:19 UTC, spt30 commented on src/pages/Game/Game.tsx
> +    window.addEventListener('keyup', (key) => {
обработчики надо вешать в componentDidMount и убирать в componentWillUnmount

2021-04-02 14:19 UTC, spt30 commented on src/pages/Game/Game.tsx
> +      <div className="game">
Хорошо бы сделать генерацию классов через библиотеку
Мне, например, нравится https://www.npmjs.com/package/b_

2021-04-02 14:19 UTC, spt30 commented on src/pages/Game/Game.tsx
> +        <div id="form" className="form">
это не по БЭМ

2021-04-05 21:32 UTC, kerimov95 commented on src/pages/Game/Game.tsx
> +  fps: number = 1000 / 120;
Так красивее выглядит

2021-04-05 21:52 UTC, kerimov95 commented on src/pages/Game/Game.tsx
> +      <div className="game">
В следующем спринте

2021-04-06 19:38 UTC, spt30 commented on src/pages/Game/Game.tsx
> +  width = 500;
Имел в виду в начало файла, сори)

2021-04-06 19:41 UTC, spt30 approved these changes
> Сложная конструкция)

Очень сложная, это правда
Вообще писать игру на реакте — то еще удовольствие. Я бы предложил вынести всякие расчеты в отдельную папку core и там воровать и убивать, оставлять кучу комментариев, выполнять расчеты. А в pages оставить чистенький такой фронтенд.

2021-04-06 22:19 UTC, merged